services:
  bash:
    build: 
      context: .
      args:
        HOST_UID: ${HOST_UID:-185}
        HOST_GID: ${HOST_GID:-185}
    user: "${HOST_UID:-185}:${HOST_GID:-185}"
    env_file: "./.env"
    volumes:
      - ./work-dir:/opt/spark/work-dir
      - ../credentials/:/opt/spark/credentials
    ports:
      - "4040:4045"
    stdin_open: true  
    tty: true        
